version: '3'
services:
  web:
    build: .
    container_name: web
    ports:
      - 127.0.0.1:8080:8080
    restart: always
  
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    env_file: .env

  database:
    container_name: database
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file: .env

  cache:
    container_name: cache
    image: redis:latest
    ports:
      - 6379:6379
    env_file: .env
      
